# Generated by Django 5.1.3 on 2024-11-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0004_newspage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutpage",
            options={"verbose_name": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="catalogpage",
            options={"verbose_name": "Каталог"},
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Главная страница"},
        ),
        migrations.AlterModelOptions(
            name="newspage",
            options={"verbose_name": "Новости"},
        ),
        migrations.AlterModelOptions(
            name="optpage",
            options={"verbose_name": "Оптовикам"},
        ),
    ]
