# Generated by Django 5.1.3 on 2024-11-17 19:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0006_stockspage_stocksformfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockspage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Текст, который будет отображаться перед формой."
            ),
        ),
        migrations.AlterField(
            model_name="stockspage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Сообщение, отображаемое после отправки формы."
            ),
        ),
    ]
