# Generated by Django 5.1.3 on 2024-11-17 19:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0008_stocksform_remove_stockspage_page_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StocksFormSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название формы для админки", max_length=255
                    ),
                ),
                (
                    "success_message",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Сообщение, которое будет отображено после отправки.",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="stocksformsubmission",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="mypages.stocksformsnippet",
            ),
        ),
        migrations.DeleteModel(
            name="StocksForm",
        ),
    ]
