# Generated by Django 5.1.3 on 2024-11-17 21:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0010_remove_stocksformsubmission_form"),
        ("wagtailcore", "0095_formsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThankYouPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Страница благодарности",
            },
            bases=("wagtailcore.page",),
        ),
    ]
