# Generated by Django 5.1.3 on 2024-11-25 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0011_thankyoupage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя клиента")),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, verbose_name="Рейтинг"),
                ),
                (
                    "video",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на видео отзыв"
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Фотография клиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
