# Generated by Django 5.1.3 on 2024-11-25 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0012_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocksformsnippet",
            options={"verbose_name": "Заявка"},
        ),
    ]
