# Generated by Django 5.1.3 on 2024-11-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0013_alter_stocksformsnippet_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocksformsnippet",
            options={},
        ),
    ]
