# Generated by Django 5.1.3 on 2024-11-17 17:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_category_categorypage_productpage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpage",
            name="specifications",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Характеристики товара"
            ),
        ),
    ]
